"""Builds the ברוש + חרדל (Cypress + Mustard) kit, chosen 2026-09-28: tokens, marks, icons, PNGs.

Stdlib only; PNGs are rendered by headless Chrome so the wordmark uses the real IBM Plex from
Google Fonts. Run from the repo root:  uv run --with pillow python brand/tools/build_cypress.py
"""
import json, os, struct, subprocess, tempfile, math

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, 'kit')
CHROME = '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'

# ---- colour ----------------------------------------------------------------
def rgb(h): h = h.lstrip('#'); return [int(h[i:i + 2], 16) for i in (0, 2, 4)]
def hx(c): return '#' + ''.join(f'{max(0, min(255, round(v))):02X}' for v in c)
def mix(a, b, pct):  # same as CSS color-mix(in srgb, a pct%, b)
    A, B = rgb(a), rgb(b); t = pct / 100; return hx([A[i] * t + B[i] * (1 - t) for i in range(3)])
def lum(h):
    def ch(v):
        v /= 255; return v / 12.92 if v <= .03928 else ((v + .055) / 1.055) ** 2.4
    r, g, b = (ch(v) for v in rgb(h)); return .2126 * r + .7152 * g + .0722 * b
def ratio(a, b):
    x, y = sorted([lum(a), lum(b)], reverse=True); return (x + .05) / (y + .05)

# The four the owner chose, and their roles in 60/30/10.
CYPRESS, SAND, MUSTARD, INK = '#004643', '#F0EDE5', '#F9C23C', '#0E1F1E'

DAY = {
    'bg': SAND, 'bg-tint': mix(CYPRESS, SAND, 6), 'surface': '#FFFFFF', 'surface-2': mix('#FFFFFF', SAND, 55),
    'line': mix(INK, SAND, 11), 'line-strong': mix(INK, SAND, 20),
    'text': INK, 'text-2': mix(INK, SAND, 76), 'text-3': mix(INK, SAND, 62),
    'brand': CYPRESS, 'on-brand': SAND, 'brand-soft': mix(CYPRESS, '#FFFFFF', 10),
    'action': MUSTARD, 'on-action': CYPRESS, 'action-soft': mix(MUSTARD, '#FFFFFF', 22),
    'lens': MUSTARD, 'link': CYPRESS,
    'success': CYPRESS, 'danger': '#B03A2E', 'on-danger': '#FFFFFF',
}
NIGHT = {
    'bg': '#0A1817', 'bg-tint': '#0E1F1E', 'surface': '#122725', 'surface-2': '#17302D',
    'line': mix('#EDE9DF', '#0A1817', 13), 'line-strong': mix('#EDE9DF', '#0A1817', 22),
    'text': '#EDE9DF', 'text-2': mix('#EDE9DF', '#0A1817', 74), 'text-3': mix('#EDE9DF', '#0A1817', 58),
    'brand': '#1F6B64', 'on-brand': '#EDE9DF', 'brand-soft': mix('#5FA89F', '#0A1817', 18),
    'action': MUSTARD, 'on-action': INK, 'action-soft': mix(MUSTARD, '#0A1817', 20),
    'lens': MUSTARD, 'link': '#7CC4BA',
    'success': '#7CC4BA', 'danger': '#F08A7E', 'on-danger': INK,
}
SHABBAT = {  # ink and candle, the same in every palette the owner looked at
    'bg': '#17150F', 'bg-tint': '#1C1A13', 'surface': '#221F17', 'surface-2': '#2A261C',
    'line': mix('#F3E9D2', '#17150F', 13), 'line-strong': mix('#F3E9D2', '#17150F', 22),
    'text': '#F3E9D2', 'text-2': mix('#F3E9D2', '#17150F', 74), 'text-3': mix('#F3E9D2', '#17150F', 58),
    'brand': '#2B4A45', 'on-brand': '#F3E9D2', 'brand-soft': mix('#E8B84A', '#17150F', 14),
    'action': '#E8B84A', 'on-action': '#17150F', 'action-soft': mix('#E8B84A', '#17150F', 20),
    'lens': '#E8B84A', 'link': '#E8B84A',
    'success': '#9CCFB8', 'danger': '#F08A7E', 'on-danger': '#17150F',
}
MODES = {'day': DAY, 'night': NIGHT, 'shabbat': SHABBAT}

NAMES = [  # swatch name, Hebrew, hex, role
    ('Cypress', 'ברוש', CYPRESS, '30 · brand: the band, the mark, headings on sand'),
    ('Sand', 'חול', SAND, '60 · ground'),
    ('Mustard', 'חרדל', MUSTARD, '10 · the primary action and the lens. Never as text on light'),
    ('Ink', 'דיו', INK, 'body text'),
    ('Night', 'לילה', NIGHT['bg'], 'night ground'),
    ('Candle', 'נר', SHABBAT['action'], 'Shabbat action and lens'),
    ('Shabbat ink', 'דיו שבת', SHABBAT['bg'], 'Shabbat ground'),
    ('Brick', 'לבנה', DAY['danger'], 'errors and deletes only'),
]

def checks():
    rows = []
    for mode, t in MODES.items():
        for fg, bg, what, need in [
            ('text', 'bg', 'text on ground', 4.5), ('text-2', 'bg', 'secondary text', 4.5),
            ('text-3', 'surface', 'tertiary text on card', 3.0),
            ('on-action', 'action', 'label on the action button', 4.5),
            ('on-brand', 'brand', 'text on the brand band', 4.5),
            ('link', 'surface', 'link on card', 4.5), ('danger', 'surface', 'error on card', 4.5)]:
            r = ratio(t[fg], t[bg]); rows.append((mode, what, t[fg], t[bg], round(r, 2), need, r >= need))
    return rows

# ---- files -----------------------------------------------------------------
def css():
    def block(t): return '\n'.join(f'  --allma-{k}: {v};' for k, v in t.items())
    return f"""/* Allma · ברוש + חרדל · generated by brand/tools/build_cypress.py, do not hand-edit */
:root {{
{block(DAY)}
  --allma-font: "IBM Plex Sans Hebrew", "IBM Plex Sans", system-ui, sans-serif;
}}
:root[data-hour="night"] {{
{block(NIGHT)}
  color-scheme: dark;
}}
:root[data-hour="shabbat"] {{
{block(SHABBAT)}
  color-scheme: dark;
}}
"""

def write_ase(path, groups):
    blocks = []
    def nb(s): s += '\0'; return struct.pack('>H', len(s)) + s.encode('utf-16-be')
    for g, items in groups:
        n = nb('Allma ' + g); blocks.append(struct.pack('>HI', 0xC001, len(n)) + n)
        for name, h in items:
            r, gg, b = (c / 255 for c in rgb(h))
            body = nb(name) + b'RGB ' + struct.pack('>fffH', r, gg, b, 2)
            blocks.append(struct.pack('>HI', 0x0001, len(body)) + body)
        blocks.append(struct.pack('>HI', 0xC002, 0))
    with open(path, 'wb') as f: f.write(b'ASEF' + struct.pack('>HHI', 1, 0, len(blocks)) + b''.join(blocks))

# ---- marks -----------------------------------------------------------------
def split_svg(d=CYPRESS, l=SAND, a=MUSTARD, size=None):
    s = f' width="{size}" height="{size}"' if size else ''
    return f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120"{s}><title>Allma</title><defs><clipPath id="a"><circle cx="42" cy="60" r="28"/></clipPath></defs><rect width="60" height="120" fill="{d}"/><rect x="60" width="60" height="120" fill="{l}"/><circle cx="42" cy="60" r="28" fill="{l}"/><circle cx="78" cy="60" r="28" fill="{d}"/><circle cx="78" cy="60" r="28" fill="{a}" clip-path="url(#a)"/></svg>'''

def round_svg(d=CYPRESS, l=SAND, a=MUSTARD, size=None, ring=None):
    s = f' width="{size}" height="{size}"' if size else ''
    rg = f'<circle cx="60" cy="60" r="58.25" fill="none" stroke="{ring}" stroke-width="3.5"/>' if ring else ''
    return f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120"{s}><title>Allma</title><defs><clipPath id="c"><circle cx="60" cy="60" r="60"/></clipPath><clipPath id="a"><circle cx="44" cy="60" r="24"/></clipPath></defs><g clip-path="url(#c)"><rect width="60" height="120" fill="{d}"/><rect x="60" width="60" height="120" fill="{l}"/><circle cx="44" cy="60" r="24" fill="{l}"/><circle cx="76" cy="60" r="24" fill="{d}"/><circle cx="76" cy="60" r="24" fill="{a}" clip-path="url(#a)"/></g>{rg}</svg>'''

def lens(cx1, cx2, cy, r):
    h = math.sqrt(r * r - ((cx2 - cx1) / 2) ** 2); x = (cx1 + cx2) / 2
    return f'M{x} {cy - h:.2f}A{r} {r} 0 0 1 {x} {cy + h:.2f}A{r} {r} 0 0 1 {x} {cy - h:.2f}Z'

S = 'fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round"'
L = 'fill="var(--lens, none)" stroke="none"'
ICONS = {  # the tab-bar set: the lens fills only on the active tab (set --lens on it)
    'home': f'<path d="M4 10.6 12 4l8 6.6V19a1.8 1.8 0 0 1-1.8 1.8H5.8A1.8 1.8 0 0 1 4 19z" {S}/><path d="{lens(10.4, 13.6, 15, 2.6)}" {L}/><circle cx="10.4" cy="15" r="2.6" fill="none" stroke="currentColor" stroke-width="1.5"/><circle cx="13.6" cy="15" r="2.6" fill="none" stroke="currentColor" stroke-width="1.5"/>',
    'tasks': f'<circle cx="18.2" cy="6.5" r="2.3" {L}/><circle cx="18.2" cy="6.5" r="2.3" {S}/><circle cx="18.2" cy="12" r="2.3" {S}/><circle cx="18.2" cy="17.5" r="2.3" {S}/><path d="M4 6.5h9.6M4 12h9.6M4 17.5h9.6" {S}/>',
    'calendar': f'<rect x="3.5" y="5" width="17" height="15.5" rx="2.6" {S}/><path d="M8 3v4M16 3v4M3.5 9.6h17" {S}/><circle cx="15.4" cy="14.9" r="2.4" {L}/><circle cx="15.4" cy="14.9" r="2.4" fill="none" stroke="currentColor" stroke-width="1.6"/>',
    'friends': f'<path d="{lens(9.5, 14.5, 8.6, 3.4)}" {L}/><circle cx="9.5" cy="8.6" r="3.4" {S}/><circle cx="14.5" cy="8.6" r="3.4" {S}/><path d="M2.8 19.6c.7-3.3 3.4-5.2 6.7-5.2M21.2 19.6c-.7-3.3-3.4-5.2-6.7-5.2M9.5 14.4h5" {S}/>',
    'profile': f'<path d="M12 4.8a3.8 3.8 0 0 1 0 7.6z" {L}/><circle cx="12" cy="8.6" r="3.8" {S}/><path d="M4.8 20c.8-3.6 3.6-5.6 7.2-5.6s6.4 2 7.2 5.6" {S}/>',
}

FONT = '<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans+Hebrew:wght@600;700&family=IBM+Plex+Sans:wght@600;700&display=swap">'
def lockup_html(lang, fg, bg, mk, ring=None):
    word = 'עולמה' if lang == 'he' else 'allma'
    d = 'rtl' if lang == 'he' else 'ltr'
    back = 'transparent' if bg is None else bg
    return f'''<!doctype html><meta charset="utf-8">{FONT}<style>html,body{{margin:0;background:{back}}}
.l{{display:flex;align-items:center;gap:44px;padding:60px 80px;direction:{d};font-family:"IBM Plex Sans Hebrew","IBM Plex Sans",sans-serif;font-weight:700;font-size:200px;line-height:1;letter-spacing:-.02em;color:{fg};width:max-content}}</style>
<div class="l">{round_svg(*mk, size=200, ring=ring)}<span>{word}</span></div>'''

def shot(html, path, w, h):
    with tempfile.NamedTemporaryFile('w', suffix='.html', delete=False) as f: f.write(html); tmp = f.name
    subprocess.run([CHROME, '--headless=new', '--hide-scrollbars', '--default-background-color=00000000',
                    f'--window-size={w},{h}', '--virtual-time-budget=6000', '--force-device-scale-factor=1',
                    f'--screenshot={path}', 'file://' + tmp], check=True, capture_output=True)
    os.unlink(tmp)

def main():
    for sub in ('tokens', 'mark', 'icons', 'png'): os.makedirs(os.path.join(OUT, sub), exist_ok=True)
    # tokens
    open(os.path.join(OUT, 'tokens', 'allma.css'), 'w').write(css())
    json.dump({'name': 'Allma · ברוש + חרדל', 'chosen': '2026-09-28', 'font': 'IBM Plex Sans Hebrew / IBM Plex Sans',
               'ratio': {'60': 'Sand', '30': 'Cypress', '10': 'Mustard'},
               'swatches': [{'name': n, 'he': he, 'hex': h, 'role': r} for n, he, h, r in NAMES],
               'modes': MODES, 'contrast': [dict(zip(('mode', 'what', 'fg', 'bg', 'ratio', 'needs', 'pass'), r)) for r in checks()]},
              open(os.path.join(OUT, 'tokens', 'allma.json'), 'w'), ensure_ascii=False, indent=2)
    write_ase(os.path.join(OUT, 'tokens', 'allma.ase'), [('Core', [(n, h) for n, he, h, r in NAMES])])
    with open(os.path.join(OUT, 'tokens', 'allma.txt'), 'w') as f:
        for n, he, h, r in NAMES: f.write(f'{he}\t{n}\t{h}\t{r}\n')
    # marks
    marks = {
        'allma-split.svg': split_svg(), 'allma-round.svg': round_svg(), 'allma-round-ringed.svg': round_svg(ring=CYPRESS),
        'allma-round-night.svg': round_svg(NIGHT['bg'], '#EDE9DF', MUSTARD),
        'allma-round-shabbat.svg': round_svg(SHABBAT['bg'], SHABBAT['text'], SHABBAT['lens']),
        'allma-round-mono-dark.svg': round_svg(INK, '#FFFFFF', INK), 'allma-round-mono-light.svg': round_svg('#FFFFFF', INK, '#FFFFFF'),
    }
    for n, s in marks.items(): open(os.path.join(OUT, 'mark', n), 'w').write(s)
    for n, body in ICONS.items():
        open(os.path.join(OUT, 'icons', f'{n}.svg'), 'w').write(f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24">{body}</svg>')
    # PNGs
    page = lambda svg, bg='transparent': f'<!doctype html><style>html,body{{margin:0;background:{bg}}}svg{{display:block}}</style>{svg}'
    P = lambda n: os.path.join(OUT, 'png', n)
    shot(page(round_svg(size=640)), P('whatsapp-avatar-640.png'), 640, 640)
    shot(page(split_svg(size=1024)), P('mark-split-1024.png'), 1024, 1024)
    shot(page(round_svg(size=512)), P('icon-512.png'), 512, 512)
    shot(page(round_svg(size=180)), P('apple-touch-180.png'), 180, 180)
    shot(page(round_svg(size=32)), P('favicon-32.png'), 32, 32)
    for lang, w in (('he', 1180), ('en', 1080)):
        shot(lockup_html(lang, CYPRESS, None, (CYPRESS, SAND, MUSTARD), ring=CYPRESS), P(f'lockup-{lang}-for-light.png'), w, 320)
        shot(lockup_html(lang, SAND, None, (INK, SAND, MUSTARD), ring=SAND), P(f'lockup-{lang}-for-dark.png'), w, 320)
    shot(page(round_svg(size=512, ring=CYPRESS)), P('mark-round-ringed-512.png'), 512, 512)
    try:  # trim the transparent margin so the lockups drop straight into a layout
        from PIL import Image
        for n in os.listdir(os.path.join(OUT, 'png')):
            if n.startswith('lockup-'):
                im = Image.open(P(n)); im.crop(im.getbbox()).save(P(n), optimize=True)
    except ImportError:
        print('pillow not installed: lockups left untrimmed (run with: uv run --with pillow python ...)')
    for r in checks(): print(('PASS' if r[6] else 'FAIL'), *r[:6])

if __name__ == '__main__':
    main()
