"""The 16 coordination marks in Cypress + Mustard, approved by the owner 2026-09-28.

Source: brand/tools/coordination-marks.src.svg (the <symbol>s, drawn in
olma2/docs/design/recovered-meeting-row/icon-language.html, colours by var()).
Writes brand/kit/coordination/: a sprite, the colour tokens (day + night), and
one self-contained SVG per mark per mode. Run: python3 brand/tools/build_coord_marks.py
"""
import os, re

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, '..', 'kit', 'coordination')
DAY = {
    'mk-line': '#0E1F1E', 'mk-hi': '#FFFFFF', 'mk-paper': '#FFFFFF', 'mk-paper-s': '#E4E1D7',
    'mk-gold': '#F9C23C', 'mk-gold-s': '#CF9A1F', 'mk-violet': '#1F6B64', 'mk-violet-s': '#004643',
    'mk-lime': '#C6D62B', 'mk-lime-s': '#90A91E', 'mk-orange': '#EC8A3B', 'mk-orange-s': '#BF6621',
    'mk-blue': '#2F7F9E', 'mk-blue-s': '#1F6377', 'mk-red': '#C4513F', 'mk-red-s': '#9A3A2C',
    'mk-green': '#3F9A6E', 'mk-green-s': '#2B7453', 'mk-navy': '#123C3A', 'mk-brown': '#8A5A2B',
}
# Night swaps only the neutrals, the same rule as the original design.
NIGHT = dict(DAY, **{'mk-line': '#EDE9DF', 'mk-paper': '#1C3633', 'mk-paper-s': '#122725',
                     'mk-navy': '#BFD3CF', 'mk-brown': '#B0763A'})
MEANING = {  # what each one says, for whoever places it
    'm-crown': 'everyone can make it', 'm-cards': 'the minimum number of people is in',
    'm-sealed': 'closed', 'm-expiring': 'time is running out',
}

src = open(os.path.join(HERE, 'coordination-marks.src.svg')).read()
symbols = re.findall(r'<symbol id="(m-[a-z]+)" viewBox="([^"]+)">(.*?)</symbol>', src, re.S)
assert len(symbols) == 16, len(symbols)
os.makedirs(OUT, exist_ok=True)
for mode in ('day', 'night'):
    os.makedirs(os.path.join(OUT, mode), exist_ok=True)

def bake(body, t):
    body = re.sub(r'var\(--(mk-[a-z-]+)\)', lambda m: t[m.group(1)], body)
    assert 'var(' not in body, body
    return body

for sid, vb, body in symbols:
    for mode, t in (('day', DAY), ('night', NIGHT)):
        with open(os.path.join(OUT, mode, sid[2:] + '.svg'), 'w') as f:
            f.write(f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="{vb}" width="24" height="24">{bake(body, t)}</svg>\n')

with open(os.path.join(OUT, 'marks-sprite.svg'), 'w') as f:
    f.write('<svg xmlns="http://www.w3.org/2000/svg" width="0" height="0" style="position:absolute">\n'
            + src.strip() + '\n</svg>\n')

def block(t): return '\n'.join(f'  --{k}: {v};' for k, v in t.items())
night_only = {k: v for k, v in NIGHT.items() if DAY[k] != v}
with open(os.path.join(OUT, 'marks.css'), 'w') as f:
    f.write('/* Coordination marks · ברוש + חרדל · generated by brand/tools/build_coord_marks.py */\n'
            f':root {{\n{block(DAY)}\n}}\n:root[data-hour="night"] {{\n{block(night_only)}\n}}\n')

print(f'{len(symbols)} marks -> {os.path.relpath(OUT)} (day + night, sprite, css)')
for sid, _, _ in symbols:
    print(' ', sid, '·', MEANING.get(sid, 'meeting type'))
